# ===============================
# APPLICATION
# ===============================
spring.application.name=collage_management
server.port=8088

# ===============================
# DATABASE (POSTGRESQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/college_management
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=12345

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional (Spring Boot usually auto-detects dialect)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect